### PR TITLE
fix: markdown html codeblock format

### LINKED ISSUE #175: Bug: Severe HTML Generation Error - Incorrect Angle Bracket Parsing/Rendering
### Description
All AI models in the production environment (https://private.near.ai/) are generating fundamentally broken HTML code. The output consistently contains incorrect angle brackets, making the HTML unusable.

---
### Problem
When asked to generate simple HTML (e.g., "Create a simple HTML page that says 'Hello World'"), the model returns code with critical syntax errors:

- Open brackets < are often missing.
- Closing tags sometimes use incorrect syntax like </>.

---
### Example of Broken Output:

```
<>!DOCTYPE html>
<html> lang="en">
<head>>
    <>meta charset="UTF-8">
    <>meta name="viewport" content="width=device-width, initial-scale=1.0">
    <>title>Hello World</>title>
</>head>
<body>>
    <>h1>Hello World</>h1>
</>body>
</>html>
```

---
### Expected Behavior
The model should generate syntactically correct, standard HTML:
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hello World</title>
</head>
<body>
    <h1>Hello World</h1>
</body>
</html>
```

### PR DESCRIPTION
**Pull request by italic-jinxin**
closed #175

### CODE REVIEW

File: src/components/chat/messages/CodeBlock.tsx [hunk 1]
```diff
@@ -5,12 +5,63 @@ import { toast } from "sonner";
 import "highlight.js/styles/github-dark.min.css";
 import CodeEditor from "@/components/common/CodeEditor";
 
+
```
Comment (think-in-universe) [inline src/components/chat/messages/CodeBlock.tsx]:
```suggestion
```
