### PR TITLE
fix: switching model in one chat incorrectly updates the model for all chats

### LINKED ISSUE #48: Bug: Switching model in one chat incorrectly updates the model for all chats
### Description:
When switching the model within the current chat (for example, selecting deepseek-v3.1), the change incorrectly affects all other chats in the Chats list — every chat now shows the newly selected model.

This behavior causes confusion and data inconsistency, as each chat should retain the model(s) that were last selected for that specific conversation.

### Expected Behavior:

- Each chat should preserve its own model selection independently.
- Switching the model in one chat should only affect that specific chat.
- Other chats in the list should continue using the model(s) that were last chosen for them.

### PR DESCRIPTION
**Pull request by italic-jinxin**
closed #48

### CODE REVIEW

File: src/pages/NewChat.tsx [hunk 1]
```diff
@@ -84,7 +84,7 @@ export default function NewChat({
         },
         {
           onSuccess: async (data) => {
-            await navigate(`/c/${data.id}`);
+            await navigate(`/c/${data.id}?new=1`);
```
Comment (think-in-universe) [inline src/pages/NewChat.tsx]: Why add `?new=1`?

File: src/pages/NewChat.tsx [hunk 2]
```diff
@@ -118,7 +118,7 @@ export default function NewChat({
       queryKey: queryKeys.conversation.all,
     });
 
-    await navigate(`/c/${newConversation.id}`);
+    await navigate(`/c/${newConversation.id}?new=1`);
```
Comment (think-in-universe) [inline src/pages/NewChat.tsx]:
```suggestion
    await navigate(`/c/${newConversation.id}?new`);
```

**Review by think-in-universe — CHANGES_REQUESTED** [review]
